name: mobile_challenge_2021
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  pull_to_refresh: ^2.0.0
  customized:
    git:
      url: https://github.com/EdvaldoMartins/customized

  # Dart data class
  freezed_annotation: ^0.14.1
  freezed: ^0.14.1+3

  # Dependency Injection
  get_it: ^7.1.2
  injectable:

  # State management
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  #Network
  dio: ^4.0.0

  # Misc
  dartz: ^0.10.0-nullsafety.1
  intl: ^0.17.0
  json_annotation: ^4.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  build_resolvers: ^2.0.1

  # Testing
  mockito: ^5.0.10


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Font
      fonts:
        - asset: assets/fonts/DINNextRoundedLTPro-Bold.otf
        - asset: assets/fonts/DINNextRoundedLTPro-Regular.otf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
  assets:
    - assets/icons/
    - assets/image/
    - assets/locale/
